// padrão
GET http://localhost:3003/users
###
// filtro nome by query
GET http://localhost:3003/users?name=Maju
###
// ordenação by name ASC
GET http://localhost:3003/users/Teacher
###
// paginação

###
// todos juntos